name: user_info_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  domain:
    path: ./domain
  navigation:
    path: ./navigation
  main:
    path: ./features/main

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    
